update: workflow

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -9,35 +9,44 @@ jobs:
   test-job:
     name: TestJob
     runs-on: ubuntu-latest
-    # steps:
-    #   - name: Check out repository code
-    #     uses: actions/checkout@v3
-    #   - run: ls -alth && sh ./.github/workflows/check-version-file.sh ${{ github.base_ref }} ${{ github.head_ref }} 
     steps:
-      - name: Checkout Code
+      - name: Check out repository code
         uses: actions/checkout@v3
-        with:
-          fetch-depth: 2 # Ensure both base and head branches are fetched
+      - run: echo "$BASE_BRANCH" || echo "$HEAD_BRANCH"
+        with: 
+          BASE_BRANCH: ${{ github.base_ref }}
+          HEAD_BRANCH: ${{ github.head_ref }}
 
-      - name: Compare Branches for version.txt
-        id: check_version_file
-        run: |
-          # Check if `version.txt` is in the diff
-          if git diff --name-only origin/${{ github.event.pull_request.base.ref }} origin/${{ github.event.pull_request.head.ref }} | grep "version.txt"; then
-            echo "file_found=true" >> $GITHUB_ENV
-            exit 0
-          else
-            echo "file_found=false" >> $GITHUB_ENV
-            exit 1
-          fi
-        continue-on-error: true # Allow the job to proceed even if the script exits with an error
+      - run: ls -alth && sh ./.github/workflows/check-version-file.sh ${{ github.base_ref }} ${{ github.head_ref }} 
+        with: 
+          BASE_BRANCH: ${{ github.base_ref }}
+          HEAD_BRANCH: ${{ github.head_ref }}
+        
+    # steps:
+    #   - name: Checkout Code
+    #     uses: actions/checkout@v3
+    #     with:
+    #       fetch-depth: 2 # Ensure both base and head branches are fetched
 
-      - name: Set Exit Code
-        run: |
-          if [ "$file_found" = "true" ]; then
-            echo "version.txt is present in the changes."
-            exit 0
-          else
-            echo "version.txt is not present in the changes."
-            exit 1
-          fi
+    #   - name: Compare Branches for version.txt
+    #     id: check_version_file
+    #     run: |
+    #       # Check if `version.txt` is in the diff
+    #       if git diff --name-only origin/${{ github.event.pull_request.base.ref }} origin/${{ github.event.pull_request.head.ref }} | grep "version.txt"; then
+    #         echo "file_found=true" >> $GITHUB_ENV
+    #         exit 0
+    #       else
+    #         echo "file_found=false" >> $GITHUB_ENV
+    #         exit 1
+    #       fi
+    #     continue-on-error: true # Allow the job to proceed even if the script exits with an error
+
+    #   - name: Set Exit Code
+    #     run: |
+    #       if [ "$file_found" = "true" ]; then
+    #         echo "version.txt is present in the changes."
+    #         exit 0
+    #       else
+    #         echo "version.txt is not present in the changes."
+    #         exit 1
+    #       fi
